name: audit with tests and lint
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths-ignore:
      - '**.md'
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: setup env
        run: cp .env.sample .env

      - name: install dependencies
        run: make setup_dev

      - name: lint
        run: make lint
  
  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: setup env
        run: cp .env.sample .env

      - name: install dependencies
        run: make setup_dev

      - name: testing
        run: make cover

      # - name: Coveralls
      #   uses: AndreMiras/coveralls-python-action@v20201129
      #   with:
      #     github-token: ${{ secrets.COVERALLS_TOKEN2 }}
      #     parallel: false
      #     flag-name: Unit Test

